receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp/tempo:
    endpoint: "http://tempo:4318"
    tls: 
        insecure: true
    compression: none

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/tempo]
