version: '3.8'

services:
  grafana:
    image: groonga/pgroonga:3.2.1-alpine-12
    container_name: pgroonga
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

volumes:
  postgres_data:
